apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
data:
  # Elasticsearch
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  
  # MinIO
  MINIO_URL: "minio:9000"
  
  # Services
  CATALOG_SERVICE_URL: "http://catalog-management:8000"
  CATALOG_SERVICE_HOST: "catalog-management"
  USER_SERVICE_HOST: "user-management"