apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:
  # MinIO Credentials
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  
  # App Secrets
  SECRET_KEY: "mysecretkey"