items = [
    {"name": "Honey Crisp Apples", "description": "Sweet and crunchy, organic", "price": 4.99, "category": "Fruits", "stock_count": 30},
    {"name": "Almond Milk", "description": "Unsweetened, vanilla flavor", "price": 3.89, "category": "Dairy", "stock_count": 25},
    {"name": "Quinoa", "description": "Organic white quinoa, 1lb", "price": 6.50, "category": "Grains", "stock_count": 18},
    {"name": "Balsamic Vinegar", "description": "Aged, Modena quality", "price": 8.99, "category": "Pantry", "stock_count": 12},
    {"name": "Sourdough Bread", "description": "Artisan loaf, baked fresh", "price": 5.49, "category": "Bakery", "stock_count": 10},
    {"name": "Frozen Blueberries", "description": "Wild caught, no sugar added", "price": 4.25, "category": "Produce", "stock_count": 40},
    {"name": "Ground Beef", "description": "85% lean, grass-fed", "price": 9.99, "category": "Meat & Seafood", "stock_count": 15},
    {"name": "Spinach", "description": "Fresh baby spinach, pre-washed", "price": 3.49, "category": "Produce", "stock_count": 22},
    {"name": "Parmesan Cheese", "description": "Grated, aged 10 months", "price": 6.99, "category": "Dairy", "stock_count": 28},
    {"name": "Sea Salt", "description": "Fine grain, Mediterranean", "price": 2.99, "category": "Pantry", "stock_count": 50},
    {"name": "Chicken Breast", "description": "Boneless, skinless, organic", "price": 11.49, "category": "Meat & Seafood", "stock_count": 14},
    {"name": "Black Beans", "description": "Canned, low sodium", "price": 1.29, "category": "Pantry", "stock_count": 60},
    {"name": "Avocados", "description": "Hass variety, ripe", "price": 1.99, "category": "Produce", "stock_count": 35},
    {"name": "Peanut Butter", "description": "Creamy, all-natural", "price": 4.50, "category": "Pantry", "stock_count": 20},
    {"name": "Oatmeal", "description": "Steel cut, quick cooking", "price": 3.99, "category": "Grains", "stock_count": 32},
    {"name": "Croissants", "description": "Buttery, pack of 4", "price": 6.00, "category": "Bakery", "stock_count": 8},
    {"name": "Cod Fillet", "description": "Wild caught, frozen", "price": 13.99, "category": "Meat & Seafood", "stock_count": 10},
    {"name": "Strawberries", "description": "Fresh local punnet", "price": 5.99, "category": "Fruits", "stock_count": 15},
    {"name": "Soy Milk", "description": "Original, fortified", "price": 3.50, "category": "Dairy", "stock_count": 20},
    {"name": "Red Lentils", "description": "Dried, bulk pack", "price": 2.75, "category": "Grains", "stock_count": 45},
    {"name": "Garlic", "description": "Whole bulbs, organic", "price": 0.99, "category": "Produce", "stock_count": 100},
    {"name": "Mozzarella", "description": "Fresh balls in brine", "price": 5.50, "category": "Dairy", "stock_count": 12},
    {"name": "Pasta", "description": "Penne rigate, semolina", "price": 1.89, "category": "Pantry", "stock_count": 55},
    {"name": "Bagels", "description": "Everything seasoning, 6 pack", "price": 4.99, "category": "Bakery", "stock_count": 15},
    {"name": "Shrimp", "description": "Large, peeled and deveined", "price": 15.99, "category": "Meat & Seafood", "stock_count": 18},
    {"name": "Bananas", "description": "Fair trade, bunch", "price": 1.50, "category": "Fruits", "stock_count": 60},
    {"name": "Cottage Cheese", "description": "Low fat, high protein", "price": 3.25, "category": "Dairy", "stock_count": 24},
    {"name": "Basmati Rice", "description": "Long grain, aromatic", "price": 7.99, "category": "Grains", "stock_count": 20},
    {"name": "Olive Tapenade", "description": "Green olives and capers", "price": 4.99, "category": "Pantry", "stock_count": 10},
    {"name": "Muffins", "description": "Blueberry, fresh daily", "price": 2.50, "category": "Bakery", "stock_count": 20},
    {"name": "Turkey Breast", "description": "Sliced deli style", "price": 8.49, "category": "Meat & Seafood", "stock_count": 12},
    {"name": "Cucumber", "description": "English, seedless", "price": 1.25, "category": "Produce", "stock_count": 40},
    {"name": "Gorgonzola", "description": "Crumbled, Italian blue", "price": 6.25, "category": "Dairy", "stock_count": 14},
    {"name": "Chickpeas", "description": "Dried, organic 2lb", "price": 4.00, "category": "Grains", "stock_count": 30},
    {"name": "Marinara Sauce", "description": "Tomato and basil", "price": 3.99, "category": "Pantry", "stock_count": 25},
    {"name": "Pita Bread", "description": "Whole wheat, 5 pack", "price": 3.00, "category": "Bakery", "stock_count": 18},
    {"name": "Lamb Chops", "description": "Grass-fed, local", "price": 19.99, "category": "Meat & Seafood", "stock_count": 6},
    {"name": "Oranges", "description": "Navel, sweet and juicy", "price": 4.50, "category": "Fruits", "stock_count": 50},
    {"name": "Heavy Cream", "description": "Pasteurized, 1 pint", "price": 3.75, "category": "Dairy", "stock_count": 15},
    {"name": "Couscous", "description": "Israeli style, toasted", "price": 5.25, "category": "Grains", "stock_count": 22},
    {"name": "Dijon Mustard", "description": "Smooth and spicy", "price": 2.89, "category": "Pantry", "stock_count": 30},
    {"name": "Rye Bread", "description": "Seeded loaf, thick slice", "price": 4.25, "category": "Bakery", "stock_count": 12},
    {"name": "Pork Tenderloin", "description": "Lean, vacuum sealed", "price": 10.99, "category": "Meat & Seafood", "stock_count": 9},
    {"name": "Broccoli", "description": "Fresh crowns, organic", "price": 2.99, "category": "Produce", "stock_count": 30},
    {"name": "Feta Cheese", "description": "Greek sheep milk", "price": 7.50, "category": "Dairy", "stock_count": 16},
    {"name": "Granola", "description": "Honey and almond mix", "price": 5.99, "category": "Grains", "stock_count": 20},
    {"name": "Soy Sauce", "description": "Lower sodium, brewed", "price": 3.49, "category": "Pantry", "stock_count": 25},
    {"name": "Baguette", "description": "French style, crusty", "price": 2.25, "category": "Bakery", "stock_count": 15},
    {"name": "Tuna Steaks", "description": "Ahi grade, frozen", "price": 16.50, "category": "Meat & Seafood", "stock_count": 8},
    {"name": "Grapes", "description": "Red seedless, crisp", "price": 4.99, "category": "Fruits", "stock_count": 20},
    {"name": "Greek Yogurt", "description": "Fat-free, 32oz tub", "price": 5.49, "category": "Dairy", "stock_count": 18},
    {"name": "Wild Rice", "description": "Long grain, earthy", "price": 8.99, "category": "Grains", "stock_count": 15},
    {"name": "Pickles", "description": "Dill spears, crunchy", "price": 3.25, "category": "Pantry", "stock_count": 22},
    {"name": "Dinner Rolls", "description": "Soft yeast rolls, 12pk", "price": 4.50, "category": "Bakery", "stock_count": 10},
    {"name": "Bacon", "description": "Hickory smoked, thick cut", "price": 7.99, "category": "Meat & Seafood", "stock_count": 20},
    {"name": "Bell Peppers", "description": "Assorted colors, 3 pack", "price": 4.99, "category": "Produce", "stock_count": 25},
    {"name": "Butter", "description": "Salted, Irish style", "price": 5.99, "category": "Dairy", "stock_count": 30},
    {"name": "Cane Sugar", "description": "Organic, unrefined", "price": 4.25, "category": "Pantry", "stock_count": 40},
    {"name": "Tortillas", "description": "Flour, soft taco size", "price": 2.99, "category": "Bakery", "stock_count": 35},
    {"name": "Scallops", "description": "Sea scallops, frozen", "price": 22.99, "category": "Meat & Seafood", "stock_count": 5}
]