FROM python:3.8-slim
WORKDIR /WORKDIR
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8501
CMD ["streamlit", "run", "app/catalog.py", "--server.port=8501", "--server.address=0.0.0.0"]