FROM python:3.11-slim

WORKDIR /WORKDIR

COPY ./services/order_management/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8004
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8004", "--reload"]